(function(){
"use strict";

// HEINRICHOS_KCD2 – Würfel / Farkle-Kompass – TEST02
// Separate Hilfsdaten. Keine Änderung an f116_data.js.
// 36 eindeutig benannte Einträge aus ItemIdList v1.5, Tabelle Dice.
const DATA = {
  "metadata": {
    "module": "Würfel / Farkle-Kompass",
    "version": "TEST02",
    "language": "de",
    "recordCount": 36,
    "status": "Rohdaten vorhanden – Spawn prüfen",
    "sourceRecordCount": 36,
    "note": "Vollständige Übernahme der 36 benannten Einträge aus dem aktuellen Drive-Tab Dice. Painter’s Dice B/G/R sind dort nicht als getrennte Einträge enthalten und werden nicht geraten. Würfel-Abzeichen bleiben getrennt."
  },
  "records": [
    {
      "id": "hos_dice_farkle_favourable_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Top-Gewinnwürfel",
      "compass_group": "Top-Gewinnwürfel",
      "compass_groups": [
        "Top-Gewinnwürfel",
        "Spawn prüfen"
      ],
      "name": "Vorteilhafter Würfel",
      "english_name": "Favourable die",
      "cheat": "wh_cheat_addItem bd819743-3e32-474e-8333-bebe92b16e98",
      "info": "Sehr guter praktischer Gewinnerwürfel. Stark auf 1 / 5 / 6. Kandidat für Ramons Gewinnset.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Favourable die",
        "HeinrichOS-Wertung": "Top",
        "Praktische Tendenz / Nutzen": "Sehr guter praktischer Gewinnerwürfel. Stark auf 1 / 5 / 6. Kandidat für Ramons Gewinnset.",
        "Würfeltendenz": "Stark auf 1 / 5 / 6",
        "Cheat-Kandidat": "wh_cheat_addItem bd819743-3e32-474e-8333-bebe92b16e98",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Klare Empfehlung als Kandidat für Ramons Gewinnset.",
        "Quellbeschreibung (Deutsch)": "Ein Spielwürfel, der häufiger Glück bringt, als man erwarten würde.",
        "Seitengewichtung (1–6)": "6 0 1 1 6 4",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieFavourable",
        "UI-Rohname": "ui_nm_dieFavourable",
        "Icon-ID (Rohdaten)": "die_j",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_j",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "450.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Top-Gewinnwürfel · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_weighted_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Gewichteter Würfel",
      "english_name": "Weighted die",
      "cheat": "wh_cheat_addItem f8e3162a-dff1-4099-a60f-05be4e40f7ca",
      "info": "Extrem stark, aber ein Sonderfall. Nicht als normal farmbar darstellen.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Weighted die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Extrem stark, aber ein Sonderfall. Nicht als normal farmbar darstellen.",
        "Würfeltendenz": "Extrem starke Eins-Tendenz",
        "Cheat-Kandidat": "wh_cheat_addItem f8e3162a-dff1-4099-a60f-05be4e40f7ca",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Sehr stark, aber erst nach Spawn-Prüfung als verlässliche Empfehlung behandeln.",
        "Quellbeschreibung (Deutsch)": "Ein geheimnisvoller Würfel aus einem verfallenen Haus, der verdächtig oft eine Eins würfelt.",
        "Seitengewichtung (1–6)": "10 1 1 1 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "prepadeni_dieBarn",
        "UI-Rohname": "ui_nm_prepadeni_dieBarn",
        "Icon-ID (Rohdaten)": "die_e",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_e",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "700.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_painted_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Top-Gewinnwürfel",
      "compass_group": "Top-Gewinnwürfel",
      "compass_groups": [
        "Top-Gewinnwürfel",
        "Spawn prüfen"
      ],
      "name": "Bemalter Würfel",
      "english_name": "Painted die",
      "cheat": "wh_cheat_addItem fd2e7345-5584-49d1-a0f9-e69c51d2bdf0",
      "info": "Guter Punktewürfel, besonders wegen starker Fünf-Tendenz.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Painted die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Guter Punktewürfel, besonders wegen starker Fünf-Tendenz.",
        "Würfeltendenz": "Starke Fünf-Tendenz",
        "Cheat-Kandidat": "wh_cheat_addItem fd2e7345-5584-49d1-a0f9-e69c51d2bdf0",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Guter Gewinnkandidat. Painter’s Dice B/G/R bleiben getrennt und sind hier nicht enthalten.",
        "Quellbeschreibung (Deutsch)": "Ein mit modernen Techniken gefärbter Würfel, dessen Manipulation dadurch verborgen wird.",
        "Seitengewichtung (1–6)": "3 1 1 1 7 3",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieBlue",
        "UI-Rohname": "ui_nm_dieBlue",
        "Icon-ID (Rohdaten)": "die_r",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_r",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "650.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Top-Gewinnwürfel · Spawn prüfen",
        "Abgrenzung": "Painter’s Dice B/G/R nicht mit Painted die vermischen; Varianten-ID weiterhin offen."
      }
    },
    {
      "id": "hos_dice_farkle_odd_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Top-Gewinnwürfel",
      "compass_group": "Top-Gewinnwürfel",
      "compass_groups": [
        "Top-Gewinnwürfel",
        "Spawn prüfen"
      ],
      "name": "Ungerader Würfel",
      "english_name": "Odd die",
      "cheat": "wh_cheat_addItem 4c465f33-a20e-4428-b2f5-09cfc6c4f6d7",
      "info": "Stark auf 1 / 3 / 5. Gut, wenn nicht nur Sechser gespielt werden sollen.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Odd die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Stark auf 1 / 3 / 5. Gut, wenn nicht nur Sechser gespielt werden sollen.",
        "Würfeltendenz": "Stark auf 1 / 3 / 5",
        "Cheat-Kandidat": "wh_cheat_addItem 4c465f33-a20e-4428-b2f5-09cfc6c4f6d7",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Guter Gewinnerwürfel für eine ungerade Punkteausrichtung.",
        "Quellbeschreibung (Deutsch)": "Ein Würfel, der meistens ungerade Zahlen bevorzugt.",
        "Seitengewichtung (1–6)": "8 2 8 2 8 2",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieOdd",
        "UI-Rohname": "ui_nm_dieOdd",
        "Icon-ID (Rohdaten)": "die_k",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_k",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "500.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Top-Gewinnwürfel · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_lucky_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Top-Gewinnwürfel",
      "compass_group": "Top-Gewinnwürfel",
      "compass_groups": [
        "Top-Gewinnwürfel",
        "Spawn prüfen"
      ],
      "name": "Glückswürfel",
      "english_name": "Lucky die",
      "cheat": "wh_cheat_addItem 1bd8d5d2-f57e-48c8-8f82-df7ae1ea90d3",
      "info": "Gute Mischung aus 1 / 5 / 6. Brauchbar als Gewinner- oder Komfortwürfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Lucky die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Gute Mischung aus 1 / 5 / 6. Brauchbar als Gewinner- oder Komfortwürfel.",
        "Würfeltendenz": "Gute Mischung aus 1 / 5 / 6",
        "Cheat-Kandidat": "wh_cheat_addItem 1bd8d5d2-f57e-48c8-8f82-df7ae1ea90d3",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Praktischer Allround-Kandidat für Gewinn- oder Komfortsets.",
        "Quellbeschreibung (Deutsch)": "Wenn das Glück lächelt, sollte man zurücklächeln – sonst wirkt man verdächtig.",
        "Seitengewichtung (1–6)": "6 1 2 3 4 6",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieLucky",
        "UI-Rohname": "ui_nm_dieLucky",
        "Icon-ID (Rohdaten)": "die_o",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_o",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "600.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Top-Gewinnwürfel · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_heavenly_kingdom_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Top-Gewinnwürfel",
      "compass_group": "Top-Gewinnwürfel",
      "compass_groups": [
        "Top-Gewinnwürfel",
        "Fair & Sammler",
        "Spawn prüfen"
      ],
      "name": "Himmlischer-Königreich-Würfel",
      "english_name": "Heavenly Kingdom die",
      "cheat": "wh_cheat_addItem 8895b262-ddfb-4392-a784-eee616798c96",
      "info": "Sehr starke Eins-Tendenz. Eher Prestige- oder Luxuswürfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Heavenly Kingdom die",
        "HeinrichOS-Wertung": "Top",
        "Praktische Tendenz / Nutzen": "Sehr starke Eins-Tendenz. Eher Prestige- oder Luxuswürfel.",
        "Würfeltendenz": "Sehr starke Eins-Tendenz",
        "Cheat-Kandidat": "wh_cheat_addItem 8895b262-ddfb-4392-a784-eee616798c96",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Starker Gewinnwürfel mit zusätzlichem Prestige- und Sammlercharakter.",
        "Quellbeschreibung (Deutsch)": "Ein wundersamer Spielwürfel, der aus dem Himmlischen Königreich auf die Erde gesandt worden sein soll.",
        "Seitengewichtung (1–6)": "7 2 2 2 2 4",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieKingdomCome",
        "UI-Rohname": "ui_nm_dieKingdomCome",
        "Icon-ID (Rohdaten)": "die_kcd",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_kcd",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "1500.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Top-Gewinnwürfel · Fair & Sammler · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_cautious_cheaters_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Top-Gewinnwürfel",
      "compass_group": "Top-Gewinnwürfel",
      "compass_groups": [
        "Top-Gewinnwürfel",
        "Spawn prüfen"
      ],
      "name": "Vorsichtiger Betrügerwürfel",
      "english_name": "Cautious cheater's die",
      "cheat": "wh_cheat_addItem 23e4412b-10fe-49eb-aba0-734a121cef67",
      "info": "Solider Gewinnerwürfel auf 1 / 5 / 6, aber nicht so brutal wie Vorteilhafter oder Gewichteter Würfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Cautious cheater's die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Solider Gewinnerwürfel auf 1 / 5 / 6, aber nicht so brutal wie Vorteilhafter oder Gewichteter Würfel.",
        "Würfeltendenz": "Solide auf 1 / 5 / 6",
        "Cheat-Kandidat": "wh_cheat_addItem 23e4412b-10fe-49eb-aba0-734a121cef67",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Solider Gewinnkandidat unterhalb der stärksten Sonderwürfel.",
        "Quellbeschreibung (Deutsch)": "Ein von einem Fachmann präzise, aber unauffällig manipulierter Würfel.",
        "Seitengewichtung (1–6)": "5 3 2 3 5 3",
        "Seitenwerte (Rohdaten)": "2 1 2 3 4 5",
        "Interner Name": "die_Gamblerova_good",
        "UI-Rohname": "ui_nm_die_gamblerova_good",
        "Icon-ID (Rohdaten)": "die_f",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_f",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "470.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Top-Gewinnwürfel · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_strip_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Gute Gewinnwürfel",
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Strip-Würfel",
      "english_name": "Strip die",
      "cheat": "wh_cheat_addItem 4306e2d9-f09b-444a-b05d-79c55449ef46",
      "info": "Brauchbar, aber nicht erste Wahl. Gute Ergänzung, wenn ein Set noch nicht komplett ist.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Strip die",
        "HeinrichOS-Wertung": "Brauchbar",
        "Praktische Tendenz / Nutzen": "Brauchbar, aber nicht erste Wahl. Gute Ergänzung, wenn ein Set noch nicht komplett ist.",
        "Würfeltendenz": "Ergänzungswürfel; nicht erste Wahl",
        "Cheat-Kandidat": "wh_cheat_addItem 4306e2d9-f09b-444a-b05d-79c55449ef46",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Als Ergänzung brauchbar, aber nicht als erstes Gewinnset empfehlen.",
        "Quellbeschreibung (Deutsch)": "Der Legende nach hilft dieser Würfel dabei, so manche Frau zu entkleiden.",
        "Seitengewichtung (1–6)": "4 2 2 2 3 3",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieStripping",
        "UI-Rohname": "ui_nm_dieStripping",
        "Icon-ID (Rohdaten)": "die_o",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_o",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "670.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "TOG-Test / HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Gute Gewinnwürfel · Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_arankas_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Gute Gewinnwürfel",
      "compass_group": "Gute Gewinnwürfel",
      "compass_groups": [
        "Gute Gewinnwürfel",
        "Quest & Personen",
        "Spawn prüfen"
      ],
      "name": "Arankas Würfel",
      "english_name": "Aranka's die",
      "cheat": "wh_cheat_addItem 6a479d81-e642-40b3-92ad-0e43793f8c66",
      "info": "Starke Rohdatengewichtung auf 1 / 3 / 5. Vielversprechender Gewinnwürfel mit Questbezug.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Aranka's die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Starke Rohdatengewichtung auf 1 / 3 / 5. Vielversprechender Gewinnwürfel mit Questbezug.",
        "Würfeltendenz": "Stark auf 1 / 3 / 5",
        "Cheat-Kandidat": "wh_cheat_addItem 6a479d81-e642-40b3-92ad-0e43793f8c66",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Guter Kandidat für ein ungerades Gewinnset; Spawn und Spielwirkung prüfen.",
        "Quellbeschreibung (Deutsch)": "Aranka gab Heinrich diesen Würfel, damit er leichter gegen ihren Mann spielen kann.",
        "Seitengewichtung (1–6)": "6 1 6 1 6 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_aranka",
        "UI-Rohname": "ui_nm_Aranka_die",
        "Icon-ID (Rohdaten)": "die_f",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_f",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "340.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Gute Gewinnwürfel · Quest & Personen · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_greasy_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Gute Gewinnwürfel",
      "compass_group": "Gute Gewinnwürfel",
      "compass_groups": [
        "Gute Gewinnwürfel",
        "Spawn prüfen"
      ],
      "name": "Fettiger Würfel",
      "english_name": "Greasy die",
      "cheat": "wh_cheat_addItem 93e67a15-6545-46d3-8820-87fd690e1f0d",
      "info": "Leicht auf 1 / 3 / 5 / 6 begünstigt. Solider Allround-Kandidat.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Greasy die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Leicht auf 1 / 3 / 5 / 6 begünstigt. Solider Allround-Kandidat.",
        "Würfeltendenz": "Leicht auf 1 / 3 / 5 / 6 begünstigt",
        "Cheat-Kandidat": "wh_cheat_addItem 93e67a15-6545-46d3-8820-87fd690e1f0d",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Brauchbarer Allrounder unterhalb der Top-Würfel.",
        "Quellbeschreibung (Deutsch)": "Verlässlicher als ein normaler Würfel, aber nicht in jeder Situation.",
        "Seitengewichtung (1–6)": "3 2 3 2 3 4",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "zachranaPtacka_die_klobas",
        "UI-Rohname": "ui_nm_zachranaPtacka_klobas_die",
        "Icon-ID (Rohdaten)": "die_l",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_l",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "150.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Gute Gewinnwürfel · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_grimy_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Gute Gewinnwürfel",
      "compass_group": "Gute Gewinnwürfel",
      "compass_groups": [
        "Gute Gewinnwürfel",
        "Spawn prüfen"
      ],
      "name": "Schmutziger Würfel",
      "english_name": "Grimy die",
      "cheat": "wh_cheat_addItem 8ab8d048-2ca7-4bb4-a0d4-963555750bc9",
      "info": "Sehr starke Fünf-Tendenz, ansonsten überwiegend schwach. Guter, aber einseitiger Punktewürfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Grimy die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Sehr starke Fünf-Tendenz, ansonsten überwiegend schwach. Guter, aber einseitiger Punktewürfel.",
        "Würfeltendenz": "Sehr starke Fünf-Tendenz",
        "Cheat-Kandidat": "wh_cheat_addItem 8ab8d048-2ca7-4bb4-a0d4-963555750bc9",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Interessanter Gewinnkandidat mit starker Fünf-Ausrichtung.",
        "Quellbeschreibung (Deutsch)": "Ein unberechenbarer Würfel, der einen aus dem Regen in die Traufe bringen kann.",
        "Seitengewichtung (1–6)": "1 5 1 1 7 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "zachranaPtacka_die_mud",
        "UI-Rohname": "ui_nm_zachranaPtacka_mud_die",
        "Icon-ID (Rohdaten)": "die_c",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_c",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "230.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Gute Gewinnwürfel · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_lousy_gamblers_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Gute Gewinnwürfel",
      "compass_group": "Gute Gewinnwürfel",
      "compass_groups": [
        "Gute Gewinnwürfel",
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Würfel des lausigen Spielers",
      "english_name": "Lousy gambler's die",
      "cheat": "wh_cheat_addItem 8ee58bb4-d928-4caf-9246-9a4706299543",
      "info": "Starke Fünf-Tendenz und auffällig unbalanciert. Guter Punkte-Kandidat, aber klarer Spezialfall.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Lousy gambler's die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Starke Fünf-Tendenz und auffällig unbalanciert. Guter Punkte-Kandidat, aber klarer Spezialfall.",
        "Würfeltendenz": "Starke Fünf-Tendenz",
        "Cheat-Kandidat": "wh_cheat_addItem 8ee58bb4-d928-4caf-9246-9a4706299543",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Als Fünfer-Würfel interessant; tatsächlichen Seitenwert im Spiel prüfen.",
        "Quellbeschreibung (Deutsch)": "Ein schlecht manipulierter Würfel, dessen Unwucht deutlich auffällt.",
        "Seitengewichtung (1–6)": "2 3 2 3 7 3",
        "Seitenwerte (Rohdaten)": "1 1 2 3 4 5",
        "Interner Name": "die_Gamblerova_bad",
        "UI-Rohname": "ui_nm_die_gamblerova_bad",
        "Icon-ID (Rohdaten)": "die_d",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_d",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "160.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Gute Gewinnwürfel · Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_sad_greasers_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Gute Gewinnwürfel",
      "compass_group": "Gute Gewinnwürfel",
      "compass_groups": [
        "Gute Gewinnwürfel",
        "Quest & Personen",
        "Spawn prüfen"
      ],
      "name": "Würfel des traurigen Schmierers",
      "english_name": "Sad Greaser's die",
      "cheat": "wh_cheat_addItem 1f610871-6df4-4c86-a5a2-4df8dc6500df",
      "info": "Stark auf 1 / 2 / 5. Brauchbarer Gewinner- und Questwürfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Sad Greaser's die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Stark auf 1 / 2 / 5. Brauchbarer Gewinner- und Questwürfel.",
        "Würfeltendenz": "Stark auf 1 / 2 / 5",
        "Cheat-Kandidat": "wh_cheat_addItem 1f610871-6df4-4c86-a5a2-4df8dc6500df",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Guter Kandidat mit Personenbezug; Spawn und Spielwirkung prüfen.",
        "Quellbeschreibung (Deutsch)": "Ein blauer Würfel, der die Traurigkeit seines früheren Besitzers widerspiegelt.",
        "Seitengewichtung (1–6)": "6 6 1 1 6 3",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "zachranaPtacka_die_sad_sergeant",
        "UI-Rohname": "ui_nm_zachranaPtacka_sad_sargeant_die",
        "Icon-ID (Rohdaten)": "die_q_devil",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_q_devil",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "450.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Gute Gewinnwürfel · Quest & Personen · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_shrinking_playing_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Gute Gewinnwürfel",
      "compass_group": "Gute Gewinnwürfel",
      "compass_groups": [
        "Gute Gewinnwürfel",
        "Fair & Sammler",
        "Spawn prüfen"
      ],
      "name": "Schrumpfender Spielwürfel",
      "english_name": "Shrinking playing die",
      "cheat": "wh_cheat_addItem aa0b6bc8-e7f6-4777-b931-1ae81d7ef8da",
      "info": "Leicht auf 1 und 6 begünstigt und trotzdem nahe am fairen Würfel. Komfort- und Sammlerkandidat.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Shrinking playing die",
        "HeinrichOS-Wertung": "Gut",
        "Praktische Tendenz / Nutzen": "Leicht auf 1 und 6 begünstigt und trotzdem nahe am fairen Würfel. Komfort- und Sammlerkandidat.",
        "Würfeltendenz": "Leicht auf 1 / 6 begünstigt",
        "Cheat-Kandidat": "wh_cheat_addItem aa0b6bc8-e7f6-4777-b931-1ae81d7ef8da",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Sanfter Gewinnvorteil ohne extreme Gewichtung; im Spiel prüfen.",
        "Quellbeschreibung (Deutsch)": "Ein nur sehr leicht geladener Würfel, kaum von einem gewöhnlichen Würfel zu unterscheiden.",
        "Seitengewichtung (1–6)": "2 1 1 1 1 3",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieBalanced",
        "UI-Rohname": "ui_nm_dieBalanced",
        "Icon-ID (Rohdaten)": "die_p",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_p",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "150.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Gute Gewinnwürfel · Fair & Sammler · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_ordinary_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Fair & Sammler",
      "compass_group": "Fair & Sammler",
      "compass_groups": [
        "Fair & Sammler",
        "Spawn prüfen"
      ],
      "name": "Gewöhnlicher Würfel",
      "english_name": "Ordinary die",
      "cheat": "wh_cheat_addItem 65ccc0cd-de18-4305-9d64-42bb3c6d8d30",
      "info": "Fairer Referenzwürfel für normale Partien.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Ordinary die",
        "HeinrichOS-Wertung": "Fair",
        "Praktische Tendenz / Nutzen": "Fairer Referenzwürfel für normale Partien.",
        "Würfeltendenz": "Faire Gleichverteilung",
        "Cheat-Kandidat": "wh_cheat_addItem 65ccc0cd-de18-4305-9d64-42bb3c6d8d30",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Der saubere Vergleichsmaßstab für alle gezinkten Würfel.",
        "Quellbeschreibung (Deutsch)": "Ein gewöhnlicher Spielwürfel.",
        "Seitengewichtung (1–6)": "1 1 1 1 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieNormal",
        "UI-Rohname": "ui_nm_dieNormal",
        "Icon-ID (Rohdaten)": "die_g",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_g",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "10.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Fair & Sammler · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_hugos_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Fair & Sammler",
      "compass_group": "Fair & Sammler",
      "compass_groups": [
        "Fair & Sammler",
        "Quest & Personen",
        "Spawn prüfen"
      ],
      "name": "Hugos Würfel",
      "english_name": "Hugo's die",
      "cheat": "wh_cheat_addItem 1b1345f6-75c0-4477-b6d7-b9d73ec9d9f0",
      "info": "Fairer Würfel mit Personen- und Questbezug.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Hugo's die",
        "HeinrichOS-Wertung": "Sammler",
        "Praktische Tendenz / Nutzen": "Fairer Würfel mit Personen- und Questbezug.",
        "Würfeltendenz": "Faire Gleichverteilung",
        "Cheat-Kandidat": "wh_cheat_addItem 1b1345f6-75c0-4477-b6d7-b9d73ec9d9f0",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Eher Sammler- und Questwürfel als Gewinnwerkzeug.",
        "Quellbeschreibung (Deutsch)": "Der Würfel des treuesten Stammgasts im Loch. Er trägt sein Abbild.",
        "Seitengewichtung (1–6)": "1 1 1 1 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieSkull",
        "UI-Rohname": "ui_nm_dieSkull",
        "Icon-ID (Rohdaten)": "dieSkull",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/dice_skull.cgf",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "1000.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Fair & Sammler · Quest & Personen · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_molar_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Fair & Sammler",
      "compass_group": "Fair & Sammler",
      "compass_groups": [
        "Fair & Sammler",
        "Spawn prüfen"
      ],
      "name": "Mahlzahnwürfel",
      "english_name": "Molar die",
      "cheat": "wh_cheat_addItem dccf7f80-e965-4666-957c-dbf975381fff",
      "info": "Fairer Zahn- und Sammlerwürfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Molar die",
        "HeinrichOS-Wertung": "Sammler",
        "Praktische Tendenz / Nutzen": "Fairer Zahn- und Sammlerwürfel.",
        "Würfeltendenz": "Faire Gleichverteilung",
        "Cheat-Kandidat": "wh_cheat_addItem dccf7f80-e965-4666-957c-dbf975381fff",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Sammler- und Questcharakter; spielerisch ein fairer Referenzwürfel.",
        "Quellbeschreibung (Deutsch)": "Ein Spielwürfel aus einem Mahlzahn. Woher er stammt, möchte man lieber nicht wissen.",
        "Seitengewichtung (1–6)": "1 1 1 1 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieTeeth_a",
        "UI-Rohname": "ui_nm_dieTeeth_a",
        "Icon-ID (Rohdaten)": "dieTeeth_a",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_teeth.cgf",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "200.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Fair & Sammler · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_premolar_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Fair & Sammler",
      "compass_group": "Fair & Sammler",
      "compass_groups": [
        "Fair & Sammler",
        "Spawn prüfen"
      ],
      "name": "Vormahlzahnwürfel",
      "english_name": "Premolar die",
      "cheat": "wh_cheat_addItem 55cc9e0d-63b4-491f-a74c-098654f58e61",
      "info": "Fairer Zahn- und Sammlerwürfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Premolar die",
        "HeinrichOS-Wertung": "Sammler",
        "Praktische Tendenz / Nutzen": "Fairer Zahn- und Sammlerwürfel.",
        "Würfeltendenz": "Faire Gleichverteilung",
        "Cheat-Kandidat": "wh_cheat_addItem 55cc9e0d-63b4-491f-a74c-098654f58e61",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Sammlerwürfel und fairer Referenzkandidat.",
        "Quellbeschreibung (Deutsch)": "Ein Spielwürfel aus einem Vormahlzahn.",
        "Seitengewichtung (1–6)": "1 1 1 1 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieTeeth_b",
        "UI-Rohname": "ui_nm_dieTeeth_b",
        "Icon-ID (Rohdaten)": "dieTeeth_b",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_teeth.cgf",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "50.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Fair & Sammler · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_wisdom_tooth_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Fair & Sammler",
      "compass_group": "Fair & Sammler",
      "compass_groups": [
        "Fair & Sammler",
        "Spawn prüfen"
      ],
      "name": "Weisheitszahnwürfel",
      "english_name": "Wisdom tooth die",
      "cheat": "wh_cheat_addItem 3a6e12fe-a494-4a34-85a9-ebdf4f1d3a14",
      "info": "Fairer Zahn- und Sammlerwürfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Wisdom tooth die",
        "HeinrichOS-Wertung": "Sammler",
        "Praktische Tendenz / Nutzen": "Fairer Zahn- und Sammlerwürfel.",
        "Würfeltendenz": "Faire Gleichverteilung",
        "Cheat-Kandidat": "wh_cheat_addItem 3a6e12fe-a494-4a34-85a9-ebdf4f1d3a14",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Sammlerwürfel und fairer Referenzkandidat.",
        "Quellbeschreibung (Deutsch)": "Ein Spielwürfel aus einem Weisheitszahn.",
        "Seitengewichtung (1–6)": "1 1 1 1 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieTeeth_c",
        "UI-Rohname": "ui_nm_dieTeeth_c",
        "Icon-ID (Rohdaten)": "dieTeeth_c",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_teeth.cgf",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "50.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Fair & Sammler · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_st_stephens_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Quest & Personen",
      "compass_group": "Quest & Personen",
      "compass_groups": [
        "Fair & Sammler",
        "Quest & Personen",
        "Spawn prüfen"
      ],
      "name": "Würfel des heiligen Stephan",
      "english_name": "St. Stephen's die",
      "cheat": "wh_cheat_addItem b8c8b160-9c66-4484-ae36-e775b39e4191",
      "info": "Die Rohgewichtung ist fair; die Quellbeschreibung verspricht dennoch günstige Zahlen. Das muss im Spiel geprüft werden.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "St. Stephen's die",
        "HeinrichOS-Wertung": "Sammler",
        "Praktische Tendenz / Nutzen": "Die Rohgewichtung ist fair; die Quellbeschreibung verspricht dennoch günstige Zahlen. Das muss im Spiel geprüft werden.",
        "Würfeltendenz": "Rohgewichtung fair; Quellenwirkung offen",
        "Cheat-Kandidat": "wh_cheat_addItem b8c8b160-9c66-4484-ae36-e775b39e4191",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Sammler- und Questwürfel mit widersprüchlicher Rohbeschreibung; erst testen.",
        "Quellbeschreibung (Deutsch)": "Ein vom heiligen Stephan gesegneter Würfel, der günstige Zahlen und Schutz vor losen Steinen verspricht.",
        "Seitengewichtung (1–6)": "1 1 1 1 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_sarlatan",
        "UI-Rohname": "ui_nm_die_sarlatan",
        "Icon-ID (Rohdaten)": "die_k",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_k",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "3330.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Fair & Sammler · Quest & Personen · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_grozavs_lucky_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Quest & Personen",
      "compass_group": "Quest & Personen",
      "compass_groups": [
        "Quest & Personen",
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Grozavs Glückswürfel",
      "english_name": "Grozav's lucky die",
      "cheat": "wh_cheat_addItem c57c2cb4-5d16-4fbe-a55c-db20dd740efe",
      "info": "Extrem starke Zwei-Tendenz. Der Name ist irreführend; für direktes Punkten eher riskant.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Grozav's lucky die",
        "HeinrichOS-Wertung": "Meiden",
        "Praktische Tendenz / Nutzen": "Extrem starke Zwei-Tendenz. Der Name ist irreführend; für direktes Punkten eher riskant.",
        "Würfeltendenz": "Extrem stark auf 2",
        "Cheat-Kandidat": "wh_cheat_addItem c57c2cb4-5d16-4fbe-a55c-db20dd740efe",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Quest- und Personenwürfel; nicht als Gewinnwürfel empfehlen.",
        "Quellbeschreibung (Deutsch)": "Eigentlich ist dieser Würfel gar nicht besonders glücklich – aber das soll niemand erfahren.",
        "Seitengewichtung (1–6)": "1 10 1 1 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "zikmunduvTabor_grozavGotchaDie",
        "UI-Rohname": "ui_nm_zikmunduvTabor_grozavGotchaDie",
        "Icon-ID (Rohdaten)": "die_m",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_m",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "250.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Quest & Personen · Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_kings_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Quest & Personen",
      "compass_group": "Quest & Personen",
      "compass_groups": [
        "Quest & Personen",
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Königswürfel",
      "english_name": "King's die",
      "cheat": "wh_cheat_addItem 5a9e23d3-e8dc-4eb7-9805-3bd2fa6d8351",
      "info": "Schwerpunkt auf 2 / 3 / 4. Königlicher Sammlerwürfel, aber keine klare 1/5-Gewinnempfehlung.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "King's die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Schwerpunkt auf 2 / 3 / 4. Königlicher Sammlerwürfel, aber keine klare 1/5-Gewinnempfehlung.",
        "Würfeltendenz": "Schwerpunkt auf 2 / 3 / 4",
        "Cheat-Kandidat": "wh_cheat_addItem 5a9e23d3-e8dc-4eb7-9805-3bd2fa6d8351",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Personen- und Spezialwürfel; praktische Stärke erst im Spiel prüfen.",
        "Quellbeschreibung (Deutsch)": "Ein König braucht angeblich keinen gezinkten Würfel, weil er immer recht hat und niemals verlieren kann.",
        "Seitengewichtung (1–6)": "4 6 7 8 4 3",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_Kralova",
        "UI-Rohname": "ui_nm_die_kralova",
        "Icon-ID (Rohdaten)": "die_q",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_q",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "910.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Quest & Personen · Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_saint_antiochus_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Quest & Personen",
      "compass_group": "Quest & Personen",
      "compass_groups": [
        "Quest & Personen",
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Würfel des heiligen Antiochus",
      "english_name": "Saint Antiochus' die",
      "cheat": "wh_cheat_addItem 329d2697-b6d2-452d-9ba9-09649a607740",
      "info": "Rollt laut Rohdaten ausschließlich die Drei. Reiner Spezialwürfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Saint Antiochus' die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Rollt laut Rohdaten ausschließlich die Drei. Reiner Spezialwürfel.",
        "Würfeltendenz": "Ausschließlich 3",
        "Cheat-Kandidat": "wh_cheat_addItem 329d2697-b6d2-452d-9ba9-09649a607740",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Für Dreierkombinationen interessant, ansonsten extrem einseitig.",
        "Quellbeschreibung (Deutsch)": "Der Würfel des heiligen Antiochus würfelt immer eine Drei – niemals Zwei und besonders niemals Vier.",
        "Seitengewichtung (1–6)": "0 0 9 0 0 0",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_Antiocha",
        "UI-Rohname": "ui_nm_die_antiocha",
        "Icon-ID (Rohdaten)": "die_q",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_q",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "790.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Quest & Personen · Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_ci_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Ci-Würfel",
      "english_name": "Ci die",
      "cheat": "wh_cheat_addItem 6f0c9c31-474f-4254-9dd6-2ab54fb87060",
      "info": "Erhöhte Sechser-Gewichtung. Laut Quellbeschreibung besonders stark im Zusammenspiel mit seinen Schwestern Lu und Fer.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Ci die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Erhöhte Sechser-Gewichtung. Laut Quellbeschreibung besonders stark im Zusammenspiel mit seinen Schwestern Lu und Fer.",
        "Würfeltendenz": "Sechser-betont; Dämonen-Dreierset",
        "Cheat-Kandidat": "wh_cheat_addItem 6f0c9c31-474f-4254-9dd6-2ab54fb87060",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Nicht einzeln als Top-Gewinnwürfel verkaufen; als Teil des Dämonen-Dreiersets testen.",
        "Quellbeschreibung (Deutsch)": "Der zweite der dämonischen Würfel. Er geht gern verloren, ist mit seinen Schwestern aber sehr stark.",
        "Seitengewichtung (1–6)": "3 3 3 3 3 8",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_Ci",
        "UI-Rohname": "ui_nm_die_Ci",
        "Icon-ID (Rohdaten)": "die_r",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_r",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "1120.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_lu_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Lu-Würfel",
      "english_name": "Lu die",
      "cheat": "wh_cheat_addItem 75a0739e-fa75-4f99-be68-e1c3ba30d57e",
      "info": "Erhöhte Sechser-Gewichtung. Erster Würfel des dämonischen Dreiersets.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Lu die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Erhöhte Sechser-Gewichtung. Erster Würfel des dämonischen Dreiersets.",
        "Würfeltendenz": "Sechser-betont; Dämonen-Dreierset",
        "Cheat-Kandidat": "wh_cheat_addItem 75a0739e-fa75-4f99-be68-e1c3ba30d57e",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Zusammen mit Ci und Fer testen; einzeln keine bestätigte Top-Empfehlung.",
        "Quellbeschreibung (Deutsch)": "Der erste der dämonischen Würfel.",
        "Seitengewichtung (1–6)": "3 3 3 3 3 8",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_Lu",
        "UI-Rohname": "ui_nm_die_Lu",
        "Icon-ID (Rohdaten)": "die_r",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_r",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "1120.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_fer_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Fer-Würfel",
      "english_name": "Fer die",
      "cheat": "wh_cheat_addItem b43b8e5b-4891-48ce-a39f-143956862c96",
      "info": "Erhöhte Sechser-Gewichtung. Dritter und letzter Würfel des dämonischen Dreiersets.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Fer die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Erhöhte Sechser-Gewichtung. Dritter und letzter Würfel des dämonischen Dreiersets.",
        "Würfeltendenz": "Sechser-betont; Dämonen-Dreierset",
        "Cheat-Kandidat": "wh_cheat_addItem b43b8e5b-4891-48ce-a39f-143956862c96",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Zusammen mit Lu und Ci testen; einzeln keine bestätigte Top-Empfehlung.",
        "Quellbeschreibung (Deutsch)": "Der dritte und letzte der dämonischen Würfel.",
        "Seitengewichtung (1–6)": "3 3 3 3 3 8",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_e",
        "UI-Rohname": "ui_nm_the_die_e",
        "Icon-ID (Rohdaten)": "die_r",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_r",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "1120.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_devils_head_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Fair & Sammler",
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Teufelskopfwürfel",
      "english_name": "Devil's head die",
      "cheat": "wh_cheat_addItem 9a9d9c0d-2c94-475d-ab72-75b8ced9ac05",
      "info": "Die Rohgewichtung ist fair, aber die Teufelskopf-Seite besitzt einen abweichenden Seitenwert. Reiner Spezialfall.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Devil's head die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Die Rohgewichtung ist fair, aber die Teufelskopf-Seite besitzt einen abweichenden Seitenwert. Reiner Spezialfall.",
        "Würfeltendenz": "Fair gewichtet; besondere Teufelskopf-Seite",
        "Cheat-Kandidat": "wh_cheat_addItem 9a9d9c0d-2c94-475d-ab72-75b8ced9ac05",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Interessanter Sammler- und Spezialwürfel, aber keine einfache Gewinnempfehlung.",
        "Quellbeschreibung (Deutsch)": "Ein Würfel, der sich heiß anfühlt. Anstelle der Eins trägt er einen Teufelskopf.",
        "Seitengewichtung (1–6)": "1 1 1 1 1 1",
        "Seitenwerte (Rohdaten)": "6 1 2 3 4 5",
        "Interner Name": "dieDevil",
        "UI-Rohname": "ui_nm_dieDevil",
        "Icon-ID (Rohdaten)": "die_r_devil",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_r_devil",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "1600.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Fair & Sammler · Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_die_of_misfortune",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Würfel des Missgeschicks",
      "english_name": "Die of misfortune",
      "cheat": "wh_cheat_addItem b41171bf-9332-44ce-96fa-7e64d6e5e92a",
      "info": "Stark auf die mittleren Seiten und schwach auf 1 und 6. Für einen einfachen Gewinnkompass eher riskant.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Die of misfortune",
        "HeinrichOS-Wertung": "Risiko",
        "Praktische Tendenz / Nutzen": "Stark auf die mittleren Seiten und schwach auf 1 und 6. Für einen einfachen Gewinnkompass eher riskant.",
        "Würfeltendenz": "Mittlere Seiten stark; 1 und 6 schwach",
        "Cheat-Kandidat": "wh_cheat_addItem b41171bf-9332-44ce-96fa-7e64d6e5e92a",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Eher meiden, bis seine tatsächliche Wirkung im Spiel geprüft ist.",
        "Quellbeschreibung (Deutsch)": "Wer damit spielt, soll eher Tränen als Glück vergießen.",
        "Seitengewichtung (1–6)": "1 5 5 5 5 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieUnlucky",
        "UI-Rohname": "ui_nm_dieUnlucky",
        "Icon-ID (Rohdaten)": "die_e",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_e",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "110.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_even_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Gerader Würfel",
      "english_name": "Even die",
      "cheat": "wh_cheat_addItem 3844bfed-e66b-4e97-bea4-4bf84d90ae82",
      "info": "Stark auf 2 / 4 / 6, aber 1 und 5 sind selten. Für klassische Farkle-Punkte eher ungünstig.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Even die",
        "HeinrichOS-Wertung": "Risiko",
        "Praktische Tendenz / Nutzen": "Stark auf 2 / 4 / 6, aber 1 und 5 sind selten. Für klassische Farkle-Punkte eher ungünstig.",
        "Würfeltendenz": "Stark auf 2 / 4 / 6",
        "Cheat-Kandidat": "wh_cheat_addItem 3844bfed-e66b-4e97-bea4-4bf84d90ae82",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Nur für eine bewusste Spezialstrategie; nicht als erstes Gewinnset empfehlen.",
        "Quellbeschreibung (Deutsch)": "Ein Würfel, der zugunsten gerader Zahlen geladen wurde.",
        "Seitengewichtung (1–6)": "2 8 2 8 2 8",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieEven",
        "UI-Rohname": "ui_nm_dieEven",
        "Icon-ID (Rohdaten)": "die_i",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_i",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "660.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_holy_trinity_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Dreifaltigkeitswürfel",
      "english_name": "Holy trinity die",
      "cheat": "wh_cheat_addItem 4ede7cfe-e698-4917-a092-a01d8ac3646f",
      "info": "Sehr starke Drei-Tendenz. Spezialwürfel für Dreierkombinationen, nicht als einfacher 1/5-Gewinner.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Holy trinity die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Sehr starke Drei-Tendenz. Spezialwürfel für Dreierkombinationen, nicht als einfacher 1/5-Gewinner.",
        "Würfeltendenz": "Sehr stark auf 3",
        "Cheat-Kandidat": "wh_cheat_addItem 4ede7cfe-e698-4917-a092-a01d8ac3646f",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Interessanter Kombinationswürfel, aber kein unkomplizierter Gewinnerwürfel.",
        "Quellbeschreibung (Deutsch)": "Ein geweihter Würfel, der besonders durch häufige Dreien an die Heilige Dreifaltigkeit erinnert.",
        "Seitengewichtung (1–6)": "4 5 10 1 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieHolyTrinity",
        "UI-Rohname": "ui_nm_dieHolyTrinity",
        "Icon-ID (Rohdaten)": "die_g",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_g",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "450.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_mathematicians_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Mathematikerwürfel",
      "english_name": "Mathematician's die",
      "cheat": "wh_cheat_addItem 11834cfd-bd67-41d8-8fe7-503f5076fa1d",
      "info": "Schwerpunkt auf 2 / 3 / 4. Eher Rechen- und Spezialwürfel als klassischer Gewinnwürfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Mathematician's die",
        "HeinrichOS-Wertung": "Risiko",
        "Praktische Tendenz / Nutzen": "Schwerpunkt auf 2 / 3 / 4. Eher Rechen- und Spezialwürfel als klassischer Gewinnwürfel.",
        "Würfeltendenz": "Schwerpunkt auf 2 / 3 / 4",
        "Cheat-Kandidat": "wh_cheat_addItem 11834cfd-bd67-41d8-8fe7-503f5076fa1d",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Interessant, aber nicht erste Wahl für Ramons Gewinn-Kompass.",
        "Quellbeschreibung (Deutsch)": "Ein nach den Arbeiten eines vergessenen Mathematikers geladener Würfel, vielleicht besser für Gleichungen als fürs Spiel.",
        "Seitengewichtung (1–6)": "4 5 6 7 1 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_Matematikova",
        "UI-Rohname": "ui_nm_die_matematikova",
        "Icon-ID (Rohdaten)": "die_j",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_j",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "300.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_pie_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Kuchenwürfel",
      "english_name": "Pie die",
      "cheat": "wh_cheat_addItem ba357fbc-ba9b-46d1-a743-b31842cd9fd4",
      "info": "Starke Eins-Tendenz; Fünf und Sechs sind laut Rohgewichtung ausgeschlossen. Sehr spezieller Würfel.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Pie die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Starke Eins-Tendenz; Fünf und Sechs sind laut Rohgewichtung ausgeschlossen. Sehr spezieller Würfel.",
        "Würfeltendenz": "Stark auf 1; keine 5 / 6 in der Rohgewichtung",
        "Cheat-Kandidat": "wh_cheat_addItem ba357fbc-ba9b-46d1-a743-b31842cd9fd4",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Kann für Einsen interessant sein, bleibt aber ein auffälliger Spezialfall.",
        "Quellbeschreibung (Deutsch)": "Nicht besonders appetitlich, aber deutlich zu niedrigen Werten hin ausbalanciert.",
        "Seitengewichtung (1–6)": "6 1 3 3 0 0",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_Kolacova",
        "UI-Rohname": "ui_nm_die_kolacova",
        "Icon-ID (Rohdaten)": "die_k",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_k",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "310.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_triple_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Dreierwürfel",
      "english_name": "Triple die",
      "cheat": "wh_cheat_addItem 85e24c29-d5b7-4792-89e4-19350e3e14ac",
      "info": "Sehr starke Drei-Tendenz. Spezialwürfel für Dreierkombinationen.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Triple die",
        "HeinrichOS-Wertung": "Spezial",
        "Praktische Tendenz / Nutzen": "Sehr starke Drei-Tendenz. Spezialwürfel für Dreierkombinationen.",
        "Würfeltendenz": "Sehr stark auf 3",
        "Cheat-Kandidat": "wh_cheat_addItem 85e24c29-d5b7-4792-89e4-19350e3e14ac",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Für Dreierkombinationen interessant, aber kein universeller Gewinnwürfel.",
        "Quellbeschreibung (Deutsch)": "Aus irgendeinem Grund würfelt dieser Würfel meistens eine Drei.",
        "Seitengewichtung (1–6)": "2 1 9 1 2 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "zachranaPtacka_die_trojak",
        "UI-Rohname": "ui_nm_zachranaPtacka_trojak_die",
        "Icon-ID (Rohdaten)": "die_h",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_h",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "650.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_ubalanced_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Unausgewogener Würfel",
      "english_name": "Ubalanced die",
      "cheat": "wh_cheat_addItem 06d3757e-2882-4d75-99f9-1008a4e9d2d1",
      "info": "Leichte 1/2-Tendenz, aber insgesamt uneinheitlich. Erst prüfen, dann einordnen.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Ubalanced die",
        "HeinrichOS-Wertung": "Risiko",
        "Praktische Tendenz / Nutzen": "Leichte 1/2-Tendenz, aber insgesamt uneinheitlich. Erst prüfen, dann einordnen.",
        "Würfeltendenz": "Leicht auf 1 / 2; uneinheitlich",
        "Cheat-Kandidat": "wh_cheat_addItem 06d3757e-2882-4d75-99f9-1008a4e9d2d1",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Unklarer Sonderfall; nicht vor dem Spawn- und Spieltest empfehlen.",
        "Quellbeschreibung (Deutsch)": "Jemand wollte diesen Würfel zu seinem Vorteil laden, hat dabei aber keine gute Arbeit geleistet.",
        "Seitengewichtung (1–6)": "3 4 1 1 2 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieUnbalanced",
        "UI-Rohname": "ui_nm_dieUnbalanced",
        "Icon-ID (Rohdaten)": "die_b",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_b",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "100.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_unlucky_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Pechwürfel",
      "english_name": "Unlucky die",
      "cheat": "wh_cheat_addItem 5ca4ea9d-a556-4051-a90e-ad645eb16b80",
      "info": "Keine starke Ausrichtung auf die klassischen Punkteseiten. Für ein Komfort-Gewinnset eher ungeeignet.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Unlucky die",
        "HeinrichOS-Wertung": "Meiden",
        "Praktische Tendenz / Nutzen": "Keine starke Ausrichtung auf die klassischen Punkteseiten. Für ein Komfort-Gewinnset eher ungeeignet.",
        "Würfeltendenz": "Schwache 1; insgesamt wenig vorteilhaft",
        "Cheat-Kandidat": "wh_cheat_addItem 5ca4ea9d-a556-4051-a90e-ad645eb16b80",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Eher meiden; nur als Sammler- oder Herausforderungskandidat.",
        "Quellbeschreibung (Deutsch)": "Manchmal hat man Glück, manchmal nicht – mit diesem Würfel meistens nicht.",
        "Seitengewichtung (1–6)": "1 3 2 2 2 1",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "dieAdversity",
        "UI-Rohname": "ui_nm_dieAdversity",
        "Icon-ID (Rohdaten)": "die_c",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_c",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "140.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Spezial & Risiko · Spawn prüfen"
      }
    },
    {
      "id": "hos_dice_farkle_wagoners_die",
      "kind": "dice_farkle",
      "kind_label": "Würfel / Farkle-Kompass",
      "section": "Würfel / Farkle-Kompass",
      "group": "Spezial & Risiko",
      "compass_group": "Spezial & Risiko",
      "compass_groups": [
        "Quest & Personen",
        "Spezial & Risiko",
        "Spawn prüfen"
      ],
      "name": "Wageners Würfel",
      "english_name": "Wagoner's die",
      "cheat": "wh_cheat_addItem 1c1c88ca-61dd-4b64-965a-fd1e9a840364",
      "info": "Stark auf 2 / 3 und dadurch für schnelles klassisches Punkten eher schwach.",
      "status": "Rohdaten vorhanden – Spawn prüfen",
      "source": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
      "fields": {
        "Englischer Rohname": "Wagoner's die",
        "HeinrichOS-Wertung": "Meiden",
        "Praktische Tendenz / Nutzen": "Stark auf 2 / 3 und dadurch für schnelles klassisches Punkten eher schwach.",
        "Würfeltendenz": "Stark auf 2 / 3",
        "Cheat-Kandidat": "wh_cheat_addItem 1c1c88ca-61dd-4b64-965a-fd1e9a840364",
        "Status": "Rohdaten vorhanden – Spawn prüfen",
        "Fundort / Quellenhinweis": "Kein von Ramon bestätigter Fundort. Spawn, Darstellung und tatsächliche Spielwirkung müssen im Spiel geprüft werden.",
        "HeinrichOS-Einschätzung": "Interessanter Personenwürfel, aber keine Gewinnempfehlung.",
        "Quellbeschreibung (Deutsch)": "Der Legende nach gehörte er dem römischen Wagenlenker Arnuldus, der Gegner ermüdete oder einschläferte.",
        "Seitengewichtung (1–6)": "1 5 6 2 2 2",
        "Seitenwerte (Rohdaten)": "0 1 2 3 4 5",
        "Interner Name": "die_Vozkova",
        "UI-Rohname": "ui_nm_die_vozkova",
        "Icon-ID (Rohdaten)": "die_a",
        "Modellpfad (Rohdaten)": "manmade/task_specific_props/entertainment/games/dice/die_a",
        "Gewicht (Rohdaten)": "0.1",
        "Preis (Rohdaten)": "230.0",
        "Im Taschendiebstahl-Beutel": "Ja",
        "Quelle": "HeinrichOS-Rohdaten – ItemIdList v1.5, Tabelle Dice",
        "Kompassgruppen": "Quest & Personen · Spezial & Risiko · Spawn prüfen"
      }
    }
  ]
};
window.HEINRICHOS_DICE_FARKLE = Object.freeze({
  metadata: Object.freeze(DATA.metadata),
  records: Object.freeze(DATA.records.map(record => Object.freeze(record)))
});
})();
